package com.cxlayui.manage.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.cxlayui.manage.pojo.TestInfo;
import com.cxlayui.manage.pojo.TestInfoExample;

public interface TestInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    int countByExample(TestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    int deleteByExample(TestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    @Delete({
        "delete from test_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    @Insert({
        "insert into test_info (id, name, ",
        "age, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{age,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(TestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    int insertSelective(TestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    List<TestInfo> selectByExample(TestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    @Select({
        "select",
        "id, name, age, create_time",
        "from test_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TestInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") TestInfo record, @Param("example") TestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    int updateByExample(@Param("record") TestInfo record, @Param("example") TestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(TestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_info
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    @Update({
        "update test_info",
        "set name = #{name,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TestInfo record);
}