package com.cxlayui.manage.pojo;

import java.util.Date;

public class TestInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.id
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.name
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.age
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_info.create_time
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.id
     *
     * @return the value of test_info.id
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.id
     *
     * @param id the value for test_info.id
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.name
     *
     * @return the value of test_info.name
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.name
     *
     * @param name the value for test_info.name
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.age
     *
     * @return the value of test_info.age
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.age
     *
     * @param age the value for test_info.age
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_info.create_time
     *
     * @return the value of test_info.create_time
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_info.create_time
     *
     * @param createTime the value for test_info.create_time
     *
     * @mbggenerated Tue Apr 24 01:29:26 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}